[workspace]
members = [
	"modules/edge-signaling",
	"modules/edge-voting",
	"modules/edge-treasury-reward",
	"node/cli",
	"node/executor",
	"node/primitives",
	"node/rpc",
	"node/rpc-client",
	"node/runtime",
]
exclude = ["vendor"]

[profile.release]
# Edgeware runtime requires unwinding.
panic = "unwind"


[patch.crates-io]
ethereum = { path = "vendor/ethereum" }