[package]
name = "edgeware-primitives"
version = "3.0.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
frame-system = { path = "../../vendor/frontier/vendor/substrate/frame/system", default-features = false }
sp-application-crypto = { path = "../../vendor/frontier/vendor/substrate/primitives/application-crypto", default-features = false }
sp-core = { path = "../../vendor/frontier/vendor/substrate/primitives/core", default-features = false }
sp-runtime = { path = "../../vendor/frontier/vendor/substrate/primitives/runtime", default-features = false }

[dev-dependencies]
sp-serializer = { path = "../../vendor/frontier/vendor/substrate/primitives/serializer" }
pretty_assertions = "0.6.1"

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-system/std",
	"sp-application-crypto/std",
	"sp-core/std",
	"sp-runtime/std",
]