[package]
name = "edgeware-inspect"
version = "3.0.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0" }
derive_more = "0.99"
log = "0.4.8"
sc-cli = { path = "../../vendor/frontier/vendor/substrate/client/cli" }
sc-client-api = { path = "../../vendor/frontier/vendor/substrate/client/api" }
sc-service = { default-features = false, path = "../../vendor/frontier/vendor/substrate/client/service" }
sp-blockchain = { path = "../../vendor/frontier/vendor/substrate/primitives/blockchain" }
sp-core = { path = "../../vendor/frontier/vendor/substrate/primitives/core" }
sp-runtime = { path = "../../vendor/frontier/vendor/substrate/primitives/runtime" }
structopt = "0.3.8"
