[package]
name = "edgeware-runtime-interface"
version = "3.0.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
description = "Edgeware runtime interface helpers and functions"
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0" }
sp-runtime = { path = "../../vendor/frontier/vendor/substrate/primitives/runtime" }
sp-runtime-interface = { path = "../../vendor/frontier/vendor/substrate/primitives/runtime-interface" }
sp-runtime-interface-proc-macro = { path = "../../vendor/frontier/vendor/substrate/primitives/runtime-interface/proc-macro" }
edgeware-primitives = { path = "../primitives" }

[features]
default = [ "std" ]
std = [
  "sp-runtime/std",
  "sp-runtime-interface/std",
]